### PR TITLE
New Widget : pingdom summary

### PR DESCRIPTION
**Pull request by MWilkinson**
Hi, 
   here's a compliment to the pingdom uptime widget - it displays a summary of all the pingdom checks, listing the number that are up, down, unknown, paused, etc, the total, and a list of the top 5 in a non-up/paused state

example job 
```ruby
require 'dashing-contrib/jobs/pingdom_summary'

DashingContrib::Jobs::PingdomSummary.run(
  every: '60s',
  event: 'pingdom-summary',
  username: ENV['PINGDOM_USERNAME'],
  password: ENV['PINGDOM_PASSWORD'],
  api_key:  ENV['PINGDOM_API_KEY'],
  list_top: 5,
  include_up: false,
)
```

example dashboard element
```html
    <li data-row='1' data-col='1' data-sizex='1' data-sizey='1'>
      <div data-id='pingdom-summary'
          data-title='Pingdom'
          data-view='PingdomSummary'></div>
    </li>
```

### CODE REVIEW

**Comment by activars** [comment]
Looks good, could you add this to wiki?

**Comment by activars** [comment]
You can create entries in the right side menu. 
https://github.com/QubitProducts/dashing-contrib/wiki

**Comment by MWilkinson** [comment]
I need to get some screen shots to add, but there's an initial pass at the wiki page

**Comment by activars** [comment]
I can add it for you if you copy and paste the doc in this Pull Request.

**Comment by MWilkinson** [comment]
:-) I'll get some sorted out shortly

**Comment by MWilkinson** [comment]
summary

Sample screen shot as requested

**Comment by activars** [comment]
I'm tagging a new version and releasing it now. Thank you!

**Pull request merged**
