### PR TITLE
Adding the HotState widget

### PR DESCRIPTION
**Pull request by geoffr**
* Derived from HotStatus, which wasn't unusable as it uses status
  not state

### CODE REVIEW

**Comment by activars** [comment]
wow, that's great. Thanks for submitting the PR. Do you mind create documentation under the wiki section here?
https://github.com/QubitProducts/dashing-contrib/wiki

You can follow the rest pages as basic format. I will merge as soon as the wiki page is done.

cheers.

**Comment by geoffr** [comment]
Wiki page done

cheers

On 2015/10/01 11:19 AM, Jing Dong wrote:
>
> wow, that's great. Thanks for submitting the PR. Do you mind create 
> documentation under the wiki section here?
> https://github.com/QubitProducts/dashing-contrib/wiki
>
> You can follow the rest pages as basic format. I will merge as soon as 
> the wiki page is done.
>
> cheers.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/QubitProducts/dashing-contrib/pull/30#issuecomment-144666499>.
>


-- 
Kind Regards

Geoff Robertson
Platform Engineer
Hetzner (Pty) Ltd

SA Contact Centre:      (T) 0861 0861 08      | (F) 0861 0861 09
International:      (T) +27 21 970 2000      | (F) +27 21 970 2001

Registration Number: 2005/023926/07
Directors: D.M. de Villiers (MD), S.M. Nortjé&  H.E. Wencke

Web: www.hetzner.co.za
Disclaimer: www.hetzner.co.za/email-disclaimer

**Comment by activars** [comment]
I'm merging it now, do you mind add a screenshot to the wiki?

**Comment by geoffr** [comment]
And done

On 2015/10/01 12:01 PM, Jing Dong wrote:
>
> I'm merging it now, do you mind add a screenshot to the wiki?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/QubitProducts/dashing-contrib/pull/30#issuecomment-144684240>.
>


-- 
Kind Regards

Geoff Robertson
Platform Engineer
Hetzner (Pty) Ltd

SA Contact Centre:      (T) 0861 0861 08      | (F) 0861 0861 09
International:      (T) +27 21 970 2000      | (F) +27 21 970 2001

Registration Number: 2005/023926/07
Directors: D.M. de Villiers (MD), S.M. Nortjé&  H.E. Wencke

Web: www.hetzner.co.za
Disclaimer: www.hetzner.co.za/email-disclaimer

**Comment by activars** [comment]
That's awesome! thanks!

**Pull request merged**
